# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: ataylorme/docker-php-advanced-wordpress-on-pantheon:latest
  working_directory: ~/pantheon-auto-updates
  environment:
    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/environment-variables/
    #
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    TERMINUS_TOKEN: YIShgNuyvKDppY0p8X6ipeFY5WcZclPc6VVTMASagOniu
    GITHUB_TOKEN:   0d2e6c2fe55077cdd1d85c6473e9195bb60c6bd2
    GIT_EMAIL: DevTeam@qiigo.com
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
    #=========================================================================
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    CIRCLE_TOKEN: 99ff0abdb7e7b381684da4d2068cb02bb84bb7ec
    TERMINUS_MACHINE_TOKEN: 202HXWDd86gg_J6B_BmmH4L_qQEhQnVyLDuNllxZSFBvx
    SLACK_HOOK_URL: https://qiigo.slack.com/messages/C4WS733V4/
    SLACK_CHANNEL: pantheon-mass-updates
    SLACK_USERNAME: DevTeam

    # The variables below usually do not need to be modified.
    
    #======================================================================================================================================
    # Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
    # Once environment variables can be expanded the variables below can be uncommented and the EXPORTs in set-up-globals.sh can be removed
    # See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
    # See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
    # See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
    #======================================================================================================================================
    # See set-up-globals.sh for more environment variables
    
    TERM: dumb

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout

            - run:
                name: declare environment variables
                command: ./.circleci/set-up-globals.sh

            - run:
                name: fire off updates on multiple sites
                command: ./.circleci/sites-to-update.sh

    check_for_updates:
        <<: *defaults
        steps:
            - checkout

            - run:
                name: declare environment variables
                command: ./.circleci/set-up-globals.sh

            - run:
                name: declare framework
                command: ./.circleci/set-framework.sh

            - run:
                name: check for updates
                command: ./.circleci/auto-update.sh
                no_output_timeout: 30m

    visual_regression_test:
        <<: *defaults
        docker:
          - image: ataylorme/docker-node-advanced-wordpress-on-pantheon:backstop-js
        steps:
            - checkout

            - run:
                name: declare environment variables
                command: ./.circleci/set-up-globals.sh

            - run:
                name: run visual regression tests
                command: ./.circleci/visual-regression-test.sh
                no_output_timeout: 30m

            - store_artifacts:
                path: /tmp/artifacts
                destination: artifacts

    lighthouse_performance_test:
        <<: *defaults
        docker:
          - image: ataylorme/docker-node-advanced-wordpress-on-pantheon:lighthouse
        steps:
            - checkout

            - run:
                name: declare environment variables
                command: ./.circleci/set-up-globals.sh

            - run:
                name: run lighthouse tests
                command: ./.circleci/lighthouse-performance-test.sh
                no_output_timeout: 30m

            - store_artifacts:
                path: /tmp/artifacts
                destination: artifacts

    behat_test:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-cache

            - run:
                name: declare environment variables
                command: ./.circleci/set-up-globals.sh

            - run:
                name: declare framework
                command: ./.circleci/set-framework.sh

            - run:
                name: run behat tests
                command: ./.circleci/behat-test.sh
                no_output_timeout: 30m

            - save_cache:
                key: composer-cache
                paths:
                    - $HOME/.composer/cache
    
    deploy_updates:
        <<: *defaults
        steps:
            - checkout

            - run:
                name: declare environment variables
                command: ./.circleci/set-up-globals.sh

            - run:
                name: declare framework
                command: ./.circleci/set-framework.sh

            - run:
                name: deploy updates
                command: ./.circleci/deploy-updates.sh
                no_output_timeout: 30m

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  update_and_test:
    triggers:
      - schedule:
          cron: "5 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
